package cz.martinbayer.e4.analyser.widgets.line;

public enum LineEventType {

	LINE_HOVERED,
	LINE_CLICKED,
	LINE_DOUBLE_CLICKED,
	LINE_DRAGGED,
	LINE_RELEASED,
	START_POINT_HOVERED,
	START_POINT_CLICKED,
	START_POINT_DOUBLE_CLICKED,
	START_POINT_DRAGGED,
	START_POINT_RELEASED,
	END_POINT_HOVERED,
	END_POINT_CLICKED,
	END_POINT_DOUBLE_CLICKED,
	END_POINT_DRAGGED,
	END_POINT_RELEASED,
}
